version: '3.8'

services:
  cliente-service:
    build:
      context: ./microservico-cliente
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - db_cliente
      - kafka
    environment:
      - DATABASE_HOST=db_cliente
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=cliente_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  pedido-service:
    build:
      context: ./microservico-pedido
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    depends_on:
      - db_pedido
      - kafka
    environment:
      - DATABASE_HOST=db_pedido
      - DATABASE_USER=root
      - DATABASE_PASSWORD=my-secret-pw
      - DATABASE_NAME=pedido_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092

  db_cliente:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=cliente_db
    volumes:
      - mysql_data_cliente:/var/lib/mysql

  db_pedido:
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=pedido_db
    volumes:
      - mysql_data_pedido:/var/lib/mysql

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "topico-cliente-criado:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

volumes:
  mysql_data_cliente:
  mysql_data_pedido:
